name: Test Cazzimiei Script

on:
  workflow_dispatch:  # permette di avviare manualmente il workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium selenium-wire

      - name: Run cazzimiei.py
        run: python cazzimiei.py
