name: Run Cazzimiei

on:
  workflow_dispatch: # lo avvii solo a mano

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install selenium selenium-wire webdriver-manager

      - name: Run scraper
        run: python cazzimiei.py

      - name: Upload playlist artifact
        uses: actions/upload-artifact@v4
        with:
          name: cazzimiei-playlist
          path: cazzimiei.m3u
