name: Build televizoeve.m3u

on:
  workflow_dispatch:   # rimuove il cron, esegui manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install selenium selenium-wire

      - name: Run script
        run: python televizoeve.py

      - name: Commit and push playlist if changed
        run: bash -c 'git config --global user.name "github-actions[bot]"; git config --global user.email "github-actions[bot]@users.noreply.github.com"; if ! git diff --quiet televizoeve.m3u; then git add televizoeve.m3u; git commit -m "🔄 Update televizoeve.m3u [skip ci]"; git push origin HEAD:main; else echo "Nessuna modifica, niente commit"; fi'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
